<?php
/***************************************************************
 * Extension config file for ext: "extbase_teste546ensionsd"
 *
 * Auto generated by Extension Porter (07.02.2015 - 22:17:21)
 ***************************************************************/
$EM_CONF[$_EXTKEY] = array(
	'title' => 'Extension Porter',
	'description' => '',
	'category' => 'plugin',
	'state' => 'test',
	'author' => 'Simon vom Eyser',
	'author_email' => 'simon.vom.eyser@gmail.com',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => '0',
	'lockType' => '',
	'author_company' => '',
	'version' => '0.0.0',
	'constraints' => array(
			'depends' => array(
				'typo3' => '6.2',
				'extbase' => '6.2',
				'fluid' => '6.2',
			),
			'conflicts' => array(
			),
			'suggests' => array(
			),
		),
);